# Generated by Django 3.1.2 on 2020-10-17 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="default-course", max_length=255)),
            ],
            options={"ordering": ["title"],},
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_active", models.BooleanField(default=True)),
                ("logged_in", models.BooleanField(default=False)),
                (
                    "last_login_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("multi_device_login", models.BooleanField(default=False)),
                ("courses", models.ManyToManyField(to="users.Course")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["user"],},
        ),
    ]
