# Generated by Django 3.1.2 on 2020-10-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20201022_0700"),
    ]

    operations = [
        migrations.AddField(
            model_name="newregistration",
            name="mobile",
            field=models.CharField(default="", max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="newregistration",
            name="name",
            field=models.CharField(max_length=1024),
        ),
    ]
